name: Build, Publish and Deploy to AKS

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PROJECT_NAME: app
  CONTAINER_REGISTRY: ${{ secrets.DOCKER_USERNAME }}

jobs:
  build-image:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: |
          echo "Building the Docker image..."
          docker build -t ${{ env.PROJECT_NAME }}:${{ github.sha }} .
          docker images  # <-- Show images for verification

  publish:
    name: Publish Docker Image
    runs-on: ubuntu-latest
    needs: build-image

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Tag Docker Image
        run: |
          docker tag ${{ env.PROJECT_NAME }}:${{ github.sha }} "maamounmribah/pfe-project:app-${{ github.sha }}"
      
      - name: Push Docker Image
        run: |
          docker push "maamounmribah/pfe-project:app-${{ github.sha }}"
    
  deploy:
    name: Deploy to AKS
    runs-on: ubuntu-latest
    needs: publish

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Get AKS credentials
        run: |
          az aks get-credentials --resource-group pfe-rg --name aks-cluster --overwrite-existing

      - name: Clone Helm Chart Repository
        run: |
          git clone https://github.com/Manel-Trabelsi/Main-Helm-Chart.git helm-chart

      - name: Deploy to AKS with Helm
        run: |
          helm upgrade --install ${{ env.PROJECT_NAME }} ./helm-chart \
            --namespace jit --create-namespace \
            --set image.tag="app-${{ github.sha }}"
